import { differenceInCalendarDays, getMonth, getYear, parseISO } from 'date-fns';
import type { APItem, ARItem, Doctor, DoctorFee, Employee, FixedAsset, InventoryItem, InventoryMovement, PayrollRecord, RevenueTransaction } from './types';
export const sum=(a:number[])=>a.reduce((x,y)=>x+(Number(y)||0),0);
export const calculateRevenueAmounts=(quantity:number,tariff:number,discount=0)=>{const grossAmount=quantity*tariff;return{grossAmount,netAmount:grossAmount-discount}};
export const groupSum=<T,>(items:T[],key:(i:T)=>string,value:(i:T)=>number)=>Object.values(items.reduce((acc,i)=>{const k=key(i)||'Lainnya';acc[k]??={name:k,value:0};acc[k].value+=value(i);return acc},{} as Record<string,{name:string;value:number}>));
export function revenueSummary(rows:RevenueTransaction[],base=new Date()){const totalRevenue=sum(rows.map(r=>r.netAmount));const month=getMonth(base),year=getYear(base);const byMonth=(m:number,y:number)=>sum(rows.filter(r=>getMonth(parseISO(r.date))===m&&getYear(parseISO(r.date))===y).map(r=>r.netAmount));const revenueCurrentMonth=byMonth(month,year);const revenuePreviousMonth=month===0?byMonth(11,year-1):byMonth(month-1,year);const revenueSameMonthLastYear=byMonth(month,year-1);const growthPercentage=(current:number,comparison:number)=>comparison?((current-comparison)/comparison)*100:0;return{totalRevenue,revenueByPayer:groupSum(rows,r=>r.payerType,r=>r.netAmount),revenueByDoctor:groupSum(rows,r=>r.doctorId,r=>r.netAmount),revenueByServiceCategory:groupSum(rows,r=>r.serviceCategory,r=>r.netAmount),revenueCurrentMonth,revenuePreviousMonth,revenueSameMonthLastYear,growthVsPrevious:growthPercentage(revenueCurrentMonth,revenuePreviousMonth),growthVsLastYear:growthPercentage(revenueCurrentMonth,revenueSameMonthLastYear)}}
export function doctorSalesRanking(transactions:RevenueTransaction[],doctors:Doctor[],fees:DoctorFee[]=[]){const totals=new Map<string,number>();transactions.forEach(r=>totals.set(r.doctorId,(totals.get(r.doctorId)||0)+r.netAmount));fees.forEach(f=>totals.set(f.doctorId,(totals.get(f.doctorId)||0)+f.netAmount));const grandTotal=sum([...totals.values()]);return [...totals].map(([doctorId,total],i)=>({rank:i+1,doctorId,doctorName:doctors.find(d=>d.id===doctorId)?.name||doctorId,total,percentage:grandTotal?total/grandTotal*100:0})).sort((a,b)=>b.total-a.total).map((r,i)=>({...r,rank:i+1}))}
export const reportHighlight=(target:number,realization:number)=>{const achievementPercentage=target?realization/target*100:0;return{target,realization,achievementPercentage,status:achievementPercentage>=100?'Tercapai':achievementPercentage>=80?'Perlu Perhatian':'Tidak Tercapai'}};
export function profitLoss(transactions:RevenueTransaction[],fees:DoctorFee[]=[],payroll:PayrollRecord[]=[]){const totalPendapatan=sum(transactions.map(t=>t.grossAmount));const totalDiskon=sum(transactions.map(t=>t.discount));const pendapatanBersih=sum(transactions.map(t=>t.netAmount));const bebanPokok=sum(fees.map(f=>f.netAmount))+pendapatanBersih*.18;const labaBruto=pendapatanBersih-bebanPokok;const bebanOperasional=sum(payroll.map(p=>p.grossSalary))+pendapatanBersih*.12;const ebitda=labaBruto-bebanOperasional;const labaRugiBersih=ebitda-pendapatanBersih*.025;return{groups:{'Pendapatan Usaha':totalPendapatan,'Pendapatan Pelayanan Medis':sum(transactions.filter(t=>['Konsultasi','Tindakan Medis','Operasi','Laboratorium'].includes(t.serviceCategory)).map(t=>t.netAmount)),'Pendapatan Farmasi':sum(transactions.filter(t=>t.serviceCategory==='Farmasi').map(t=>t.netAmount)),'Pendapatan Optik':sum(transactions.filter(t=>t.serviceCategory==='Optik').map(t=>t.netAmount)),Diskon:totalDiskon,'Beban Pokok Pendapatan':bebanPokok,'Beban Operasional':bebanOperasional,'Beban Administrasi':bebanOperasional*.3,'Pendapatan/Beban Lainnya':-pendapatanBersih*.025},totalPendapatan,totalDiskon,pendapatanBersih,bebanPokok,labaBruto,bebanOperasional,ebitda,labaRugiBersih,marginLabaBruto:pendapatanBersih?labaBruto/pendapatanBersih*100:0,marginLabaBersih:pendapatanBersih?labaRugiBersih/pendapatanBersih*100:0}}
export const budgetRealization=(budgetAmount:number,realizationAmount:number)=>({budgetAmount,realizationAmount,percentage:budgetAmount?realizationAmount/budgetAmount*100:0,variance:realizationAmount-budgetAmount,status:realizationAmount>budgetAmount?'Over Budget':'Under Budget'});
export function agingAR(items:ARItem[],asOf=new Date()){return groupAging(items,i=>i.payerName,i=>i.serviceDate||i.invoiceDate,i=>i.outstandingAmount,asOf)}
export function agingAP(items:APItem[],asOf=new Date()){return groupAging(items,i=>i.vendorName,i=>i.invoiceDate,i=>i.outstandingAmount,asOf)}
function groupAging<T>(items:T[],name:(i:T)=>string,date:(i:T)=>string,value:(i:T)=>number,asOf:Date){const rows:Record<string,any>={};items.forEach(i=>{const n=name(i),days=differenceInCalendarDays(asOf,parseISO(date(i)));rows[n]??={name:n,'0-30':0,'31-60':0,'>60':0,total:0};const b=days<=30?'0-30':days<=60?'31-60':'>60';rows[n][b]+=value(i);rows[n].total+=value(i)});return Object.values(rows)}
export function inventoryAverage(items:InventoryItem[],movements:InventoryMovement[]){return items.map(item=>{const ms=movements.filter(m=>m.itemId===item.id);const qty=(t:string)=>sum(ms.filter(m=>m.movementType===t).map(m=>m.quantity));const inQty=qty('Masuk'),outQty=qty('Keluar'),adjustmentQty=qty('Adjustment'),expiredQty=qty('Expired');const openingAmount=item.openingQty*item.wacc,inAmount=inQty*item.wacc,outAmount=outQty*item.wacc,adjustmentAmount=adjustmentQty*item.wacc,expiredAmount=expiredQty*item.wacc;return{...item,openingAmount,inQty,outQty,adjustmentQty,expiredQty,inAmount,outAmount,adjustmentAmount,expiredAmount,endingQty:item.openingQty+inQty-outQty-adjustmentQty-expiredQty,endingAmount:openingAmount+inAmount-outAmount-adjustmentAmount-expiredAmount}})}
export const fixedAssetCalc=(asset:FixedAsset)=>({...asset,totalCost:asset.quantity*asset.unitPrice,monthlyDepreciation:asset.economicLifeMonths?asset.quantity*asset.unitPrice/asset.economicLifeMonths:0,bookValue:asset.quantity*asset.unitPrice-asset.accumulatedDepreciation});
export const opticalIncentive=(sellingPrice:number,cogs:number)=>({grossProfit:sellingPrice-cogs,incentive:(sellingPrice-cogs)*.025});
export const labSharing=(examinationPrice:number)=>({doctorFee:examinationPrice*.1,sharingProfit:examinationPrice*.9});
export const doctorFeeNet=(ri:number,rj:number,additional:number,deduction:number,postTaxAdjustment:number,examinationDeduction:number,medicineOpticDeduction:number,cashWithdrawal:number)=>{const bruto=ri+rj+additional-deduction,tax=bruto/2*.05;return{bruto,tax,netto:bruto-tax-postTaxAdjustment-examinationDeduction-medicineOpticDeduction-cashWithdrawal}};
export const attendanceDeduction=(e:Employee,a:{absentWithoutNotice:number;sickWithoutLetter:number;sickWithLetter:number;unpaidLeave:number;noFingerprint:number})=>a.absentWithoutNotice*((e.mealAllowance+e.transportAllowance)*2)+a.sickWithoutLetter*(e.mealAllowance+e.transportAllowance)+a.sickWithLetter*e.transportAllowance+a.unpaidLeave*(e.mealAllowance+e.transportAllowance)+a.noFingerprint*e.transportAllowance;
export const payrollCalc=(basicSalary:number,fixedAllowances:number,variableAllowances:number,deductions:number[])=>{const grossSalary=basicSalary+fixedAllowances+variableAllowances,totalDeduction=sum(deductions);return{grossSalary,totalDeduction,takeHomePay:grossSalary-totalDeduction}};
export const ppnBalance=(previousBalance:number,debit:number,credit:number,normal:'Debit'|'Credit')=>normal==='Credit'?previousBalance-debit+credit:previousBalance+debit-credit;
