export type PayerType='Umum'|'BPJS'|'Asuransi'|'Perusahaan';
export type ServiceCategory='Administrasi'|'Konsultasi'|'Tindakan Medis'|'Operasi'|'Laboratorium'|'Farmasi'|'Optik'|'BMHP'|'Alkes'|'Lainnya';
export type PaymentMethod='Cash'|'Credit Card'|'Debit Card'|'QRIS'|'Transfer'|'Piutang BPJS'|'Piutang Asuransi'|'Piutang Perusahaan'|'Piutang Dokter'|'Piutang Karyawan'|'DP';
export interface ClinicProfile{name:string;address:string;phone:string;city:string;legalEntityName:string;clinicCode:string;financeCode:string}
export interface Doctor{id:string;name:string;specialty:string;bankName:string;bankAccountName:string;bankAccountNumber:string;npwpStatus:string;isActive:boolean}
export interface Employee{id:string;name:string;position:string;joinDate:string;basicSalary:number;fixedAllowancePosition:number;fixedAllowanceProfession:number;fixedAllowanceSkill:number;mealAllowance:number;transportAllowance:number;otherAllowance:number;employeeType:'Medis'|'Non Medis';isActive:boolean}
export interface Vendor{id:string;name:string;npwp:string;bankName:string;bankAccountName:string;bankAccountNumber:string;category:string;isActive:boolean}
export interface Payer{id:string;name:string;type:PayerType;address:string;contactPerson:string;isActive:boolean}
export interface COA{id:string;code:string;name:string;category:'Asset'|'Liability'|'Equity'|'Revenue'|'COGS'|'Expense'|'Other';normalBalance:'Debit'|'Credit';parentCode:string;isActive:boolean}
export interface RevenueTransaction{id:string;date:string;receiptNo:string;invoiceNo:string;medicalRecordNo:string;registrationNo:string;patientName:string;payerType:PayerType;payerName:string;doctorId:string;serviceCategory:ServiceCategory;serviceName:string;quantity:number;tariff:number;grossAmount:number;discount:number;netAmount:number;paymentMethod:PaymentMethod;bankName:string;costCenter:string;notes:string}
export interface DoctorFee{id:string;doctorId:string;billDate:string;actionDate:string;patientName:string;registrationNo:string;billNo:string;payerType:PayerType;payerName:string;regType:'Rawat Jalan'|'Rawat Inap'|'ODC'|'IGD';component:string;doctorFeeAmount:number;additionalAmount:number;deductionAmount:number;taxAmount:number;postTaxAdjustment:number;examinationDeduction:number;medicineOpticDeduction:number;cashWithdrawal:number;netAmount:number;paymentDate:string;paymentNo:string;notes:string}
export interface PaymentRequest{id:string;requestDate:string;requestNo:string;requestCategory:'Medis'|'Umum';requestedBy:string;department:string;vendorId:string;invoiceNo:string;amount:number;description:string;bankName:string;bankAccountName:string;bankAccountNumber:string;status:'Draft'|'Submitted'|'Approved'|'Paid'|'Cancelled';notes:string}
export interface PettyCashTransaction{date:string;description:string;debit:number;credit:number}
export interface PettyCashRequest{id:string;requestDate:string;requestNo:string;openingBalance:number;transactions:PettyCashTransaction[];endingBalance:number;requestedTopUpAmount:number;roundedTopUpAmount:number;status:string}
export interface Voucher{id:string;date:string;voucherNo:string;type:'BBK'|'BKK'|'KK'|'KKM'|'BKM'|'SB';paidTo:string;amount:number;amountInWords:string;paymentMethod:string;chequeNo:string;description:string;sourceLedgerId:string;supplierId:string;status:string;tanggal?:string;nomor?:string;terbilang?:string;sourceLedger?:string;notes?:string;createdAt?:string;updatedAt?:string}
export interface CashierDailyReport{id:string;date:string;receiptNo:string;registrationNo:string;patientName:string;payerType:PayerType;payerName:string;doctorName:string;unit:string;paymentDescription:string;cash:number;creditCard:number;debitCard:number;bpjsReceivable:number;insuranceReceivable:number;transfer:number;deposit:number;doctorEmployeeReceivable:number;cashierDiscount:number;notes:string}
export interface ARItem{id:string;serviceDate:string;invoiceDate:string;invoiceNo:string;payerId:string;payerName:string;payerType:PayerType;patientName:string;amount:number;paidAmount:number;outstandingAmount:number;status:string;notes:string}
export interface APItem{id:string;invoiceDate:string;invoiceNo:string;vendorId:string;vendorName:string;amount:number;paidAmount:number;outstandingAmount:number;status:string;notes:string}
export interface InventoryItem{id:string;itemCode:string;itemName:string;category:string;unit:string;wacc:number;openingQty:number;openingAmount:number;isActive:boolean}
export interface InventoryMovement{id:string;date:string;itemId:string;movementType:'Masuk'|'Keluar'|'Adjustment'|'Expired';quantity:number;unitCost:number;amount:number;notes:string}
export interface FixedAsset{id:string;assetCode?:string;assetName:string;assetCategory?:string;supplier?:string;supplierName:string;acquisitionDate:string;usageDate:string;quantity:number;qty?:number;unitPrice:number;acquisitionValue?:number;total?:number;totalCost:number;residualValue?:number;economicLifeMonths:number;depreciationMethod?:'straight_line';monthlyDepreciation:number;costCenter:string;accumulatedDepreciation:number;bookValue:number;status?:'Aktif'|'Nonaktif'|'Disposed';notes:string;createdAt?:string;updatedAt?:string}
export interface TaxItem{id:string;date:string;taxType:'PPh21'|'PPh23'|'PPNKeluaran'|'PPNMasukan'|'PPhHonorDokter';vendorOrPersonName:string;npwp:string;invoiceNo:string;period:string;nominal:number;dpp:number;ppn:number;pph:number;takeHomePay:number;paymentDate:string;notes:string}
export interface AttendanceRecord{id:string;period:string;employeeId:string;absentWithoutNotice:number;sickWithoutLetter:number;sickWithLetter:number;overtimeSubstituteLeave:number;unpaidLeave:number;noFingerprint:number;paidLeave:number;score:number;notes:string}
export interface PayrollRecord{id:string;period:string;employeeId:string;basicSalary:number;fixedAllowances:number;variableAllowances:number;grossSalary:number;bpjsTkDeduction:number;bpjsKsDeduction:number;attendanceDeduction:number;scoringAllowanceDeduction:number;otherDeduction:number;pph21:number;totalDeduction:number;takeHomePay:number;employeeType:'Medis'|'Non Medis';status:string}
export interface AuditEntry{id:string;timestamp:string;module:string;action:'create'|'update'|'delete'|'status-change'|'import'|'export'|'reset';entityId:string;entityLabel:string;description:string}
export interface Settings{targetRevenue:number;taxRates:{pph23:number;pph21Vendor:number;doctorNonNpwpMultiplier:number;doctorDppPercentage:number;doctorProgressiveRates:{limit:number;rate:number}[]};documentPrefixes:Record<string,string>;defaultMonth:number;defaultYear:number;activeMonth:number;activeYear:number;activeDateFrom:string;activeDateTo:string;currencyFormat:string;payerCategories:string[];serviceCategories:string[];costCenters:string[];inventoryCategories?:string[];vendorCategories?:string[];paymentMethods?:string[];equityOpeningBalance?:number}
export interface PPNLedgerEntry{id:string;date:string;glAccount:string;accountShortText:string;docNumber:string;costCenter:string;transactionType:string;debit:number;credit:number;balance:number;description:string;shortText:string;userEntry:string;category:string;normalBalance:'Debit'|'Credit'}
export interface AppData{'clinic-profile':ClinicProfile;doctors:Doctor[];employees:Employee[];vendors:Vendor[];payers:Payer[];coa:COA[];'revenue-transactions':RevenueTransaction[];'doctor-fees':DoctorFee[];'payment-requests':PaymentRequest[];'cash-requests':PettyCashRequest[];vouchers:Voucher[];'cashier-daily-reports':CashierDailyReport[];'ar-items':ARItem[];'ap-items':APItem[];'inventory-items':InventoryItem[];'inventory-movements':InventoryMovement[];'fixed-assets':FixedAsset[];'tax-items':TaxItem[];attendance:AttendanceRecord[];payroll:PayrollRecord[];settings:Settings;'ppn-ledger':PPNLedgerEntry[];'audit-trail':AuditEntry[]}
