import { Input, Select } from '@/components/ui/basic';
import type { Doctor, Payer, Vendor, Settings } from '@/lib/types';

const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
export function MonthSelector({month,year,onChange}:{month:number;year:number;onChange:(v:{month:number;year:number})=>void}){return <div className="grid gap-2 sm:flex"><Select value={month} onChange={e=>onChange({month:Number(e.target.value),year})}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</Select><Input type="number" className="w-full sm:w-28" value={year} onChange={e=>onChange({month,year:Number(e.target.value)})}/></div>}
export function DateRangeSelector({from,to,onChange}:{from:string;to:string;onChange:(v:{from:string;to:string})=>void}){return <div className="grid gap-2 sm:flex sm:flex-wrap sm:items-center"><Input type="date" value={from} onChange={e=>onChange({from:e.target.value,to})}/><span className="text-sm text-slate-500">s/d</span><Input type="date" value={to} onChange={e=>onChange({from,to:e.target.value})}/></div>}
export function MonthRangeSelector({fromMonth,toMonth,year,onChange}:{fromMonth:number;toMonth:number;year:number;onChange:(v:{fromMonth:number;toMonth:number;year:number})=>void}){return <div className="grid gap-2 sm:flex sm:flex-wrap"><Select value={fromMonth} onChange={e=>onChange({fromMonth:Number(e.target.value),toMonth,year})}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</Select><Select value={toMonth} onChange={e=>onChange({fromMonth,toMonth:Number(e.target.value),year})}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</Select><Input type="number" className="w-full sm:w-28" value={year} onChange={e=>onChange({fromMonth,toMonth,year:Number(e.target.value)})}/></div>}
export function PeriodSelector({settings,onChange}:{settings:Settings;onChange:(settings:Settings)=>void}){return <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 md:grid-cols-2"><label className="space-y-1"><span className="text-xs font-semibold uppercase text-slate-500">Periode Global</span><MonthSelector month={settings.activeMonth??settings.defaultMonth} year={settings.activeYear??settings.defaultYear} onChange={v=>onChange({...settings,activeMonth:v.month,activeYear:v.year})}/></label><label className="space-y-1"><span className="text-xs font-semibold uppercase text-slate-500">Tanggal Aktif</span><DateRangeSelector from={settings.activeDateFrom??`${settings.defaultYear}-${String(settings.defaultMonth).padStart(2,'0')}-01`} to={settings.activeDateTo??`${settings.defaultYear}-${String(settings.defaultMonth).padStart(2,'0')}-31`} onChange={v=>onChange({...settings,activeDateFrom:v.from,activeDateTo:v.to})}/></label></div>}
export function CommonFilters({doctors=[],payers=[],vendors=[],settings}:{doctors?:Doctor[];payers?:Payer[];vendors?:Vendor[];settings?:Settings}){return <div className="grid gap-2 sm:flex sm:flex-wrap"><Select><option>Semua Dokter</option>{doctors.map(d=><option key={d.id}>{d.name}</option>)}</Select><Select><option>Semua Payer</option>{payers.map(p=><option key={p.id}>{p.name}</option>)}</Select><Select><option>Semua Vendor</option>{vendors.map(v=><option key={v.id}>{v.name}</option>)}</Select><Select><option>Semua Cost Center</option>{settings?.costCenters.map(c=><option key={c}>{c}</option>)}</Select><Select><option>Semua Kategori</option>{settings?.serviceCategories.map(c=><option key={c}>{c}</option>)}</Select><Select><option>Semua Metode Bayar</option><option>Cash</option><option>Debit Card</option><option>Credit Card</option><option>Transfer</option><option>QRIS</option><option>Piutang BPJS</option><option>Piutang Asuransi</option></Select><Select><option>Semua Status</option><option>Draft</option><option>Submitted</option><option>Approved</option><option>Paid</option><option>Overdue</option></Select><Select><option>Semua Pajak</option><option>PPh21</option><option>PPh23</option><option>PPN</option><option>PPhHonorDokter</option></Select></div>}
